### ISSUE TITLE
I can't build it.

### ISSUE THREAD

**Issue by ghost** [ivan-kadyka/Browser.WebView2.WPF#7]
When I go to build this from source it complains about a missing dll for _**every single project**_.

**Comment by ivan-kadyka** [comment]
Hello @mimmeer-github,
Current project has CI/CD via GitHub Actions to build and publish. It definitely works properly for building the solution project. 
  From my side question-advises to check your environment:
- Are you running on Windows os?
- Have you installed .NET 6? 
- Have you resolved Nuget packages?
